### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by MikeGrace** [awerkamp/markdown-scriptures-standard-works-church-of-jesus-christ#2]
https://github.com/awerkamp/markdown-scriptures-standard-works-church-of-jesus-christ/blame/4d5625e34a5a35fdac3199d5a266c4f7669a1f19/Book%20of%20Mormon/01%201%20Nephi/1nephi06.md#L9C8-L9C8

I noticed a comment in this file. Not sure if it was your intention to have this as part of the standard works repo.

**Comment by awerkamp** [comment]
Thank you. I need to get the removed. I appreciate it.

**Comment by MikeGrace** [comment]
Any time. Scanning through a few other chapters it looks like there are other files that have comments as well.

**Comment by awerkamp** [comment]
Thank you Mike. Can you let me know of any you have come across? I would be surprised if there are more than a few but I could be wrong. Benjamin AwerkampOn Jul 19, 2023, at 12:30 PM, Mike Grace ***@***.***> wrote:﻿
Any time. Scanning through a few other chapters it looks like there are other files that have comments as well.

**Comment by MikeGrace** [comment]
How about a pull request?
