### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by njcrowther** [awerkamp/markdown-scriptures-standard-works-church-of-jesus-christ#5]
Not an issue, just wanted to say thank you for making this so I didn't have to today. This is exactly what I need for Obsidian!

**Comment by awerkamp** [comment]
You're welcome!

**Comment by joehays** [comment]
Indeed. Thank you!

**Comment by MikeGrace** [comment]
I'll second that. Thank you.

**Comment by ethanporcaro** [comment]
Amazing resource. I'll be using this to digitize my paper notes with Obsidian!
- Elder Porcaro
