### ISSUE TITLE
General Conference Talks

### ISSUE THREAD

**Issue by joehays** [awerkamp/markdown-scriptures-standard-works-church-of-jesus-christ#6]
I'm not sure what tools you use to create these files... do you have the infrastructure to make General Conference talks?

I suspect that licensing does not allow these beyond personal use. But, my interests are for personal use.

Have you ever made these? Would you consider making them? If not, do you have tools to help make them?

**Comment by MikeGrace** [comment]
I use Keyboard Maestro to run through a list of links and scrape the contents to files.

**Comment by awerkamp** [comment]
That would be outside of what I have time for but I would absolutely love if someone put that together.
