### ISSUE TITLE
Dendron support

### ISSUE THREAD

**Issue by joehays** [awerkamp/markdown-scriptures-standard-works-church-of-jesus-christ#7]
I'm a [Dendron ](https://www.dendron.so/) user. It's very similar to Obsidian but uses a flat folder hierarchy. I've made the conversion already. Is there any value in a pull request adding a folder (say "dendron-md-scriptures") for the same content in the flat hierarchy?

Or, should we just leave it up to users to do that on their own.

**Comment by MikeGrace** [comment]
Nice! Dendron does look similar. I like that idea but not my repo so I'll just say +1 from me.

**Comment by awerkamp** [comment]
Hey Joe, nice to meet you. Have you tried using this in Dendron already? I looked up some of the [documentation](https://wiki.dendron.so/notes/hur7r6gr3kqa56s2vme986j/) and it looks like Dendron should be able to handle multi-level hierarchies.
